services:
  arb_bot:
    image: rainprotocol/arb_bot:${DOCKER_CHANNEL}
    env_file: .env
    restart: always
    logging:
      driver: local
    pull_policy: always
    volumes:
      - "rainprotocol-arb-bot:/etc/rainprotocol/arb-bot:Z"

volumes:
  rainprotocol-arb-bot:
    external:
      name: rainprotocol-arb-bot-${DOCKER_CHANNEL}