name: Take Orders

# modify the cron schedule to your desired schedule
on:
  schedule:
    - cron:  '0/5 * * * *'

jobs:
  take-orders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install NodeJS v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      # pass the required values as github secrets to the bot
      - name: Take Orders
        run: node ./run.js -k ${{ secrets.BOT_WALLET_PRIVATEKEY }} -r ${{ secrets.RPC_URL }} --orderbook-address 0xd14c2ba8779c6c4fba0d0606f4ff65ecd4c5bb38 --arb-address 0x828695f98445da3a64065dacef10efc29f7024bb